AWSTemplateFormatVersion: 2010-09-09

Resources:
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: GroupName-SG
      GroupDescription: GroupDescription-SG
      VpcId: !ImportValue MyVPC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SGfromCF

Outputs:
  SG1:
    Value : !Ref secGroupName
    Export:
      Name: SG1Name